### ISSUE TITLE
[BUG]: button size in collage process

### ISSUE THREAD

**Issue by mhellmeier** [andi34/photobooth#317]
**Describe the bug**

When starting the collage creation process, the Cancel-button has the wrong height. Further, it always shows "Please wait..." above the button (even if the language is changed in the config).

**To Reproduce**
1. Change language
2. Adjust font size
3. Make collage

**Expected behavior**

Same button height as the others and a translation of "Please wait".

**Screenshots**

![collage-error](https://user-images.githubusercontent.com/1036284/133942064-6b6a3447-a627-4408-8b0c-1287f046afeb.png)

**Environment (please complete the following information):**
 - OS: Raspberry Pi
 - Browser: Chromium
 - Version: Latest dev branch

**Photobooth**
- Did it work before? no
- Which version of Photobooth are you using? Latest dev branch

**Comment by mhellmeier** [comment]
I fixed the button-size problem in the main repo: https://github.com/andreknieriem/photobooth/pull/281

**Comment by andi34** [comment]
Thanks, I'll take a look at the button tomorrow. The main repo isn't worked on anymore.

There's no bug regarding the language, "Please wait..." wasn't translated into German yet.
Translation need to be done in crowdin: https://crowdin.com/project/photobooth

**Comment by andi34** [comment]
Doesn't seem to fix it and really related to the resolution of your device.

![Screenshot_20210920-111942](https://user-images.githubusercontent.com/6080900/133982693-0e84cdc0-d1a8-49b8-a04c-5c68d3263a91.png)

![Screenshot_20210920-111927](https://user-images.githubusercontent.com/6080900/133982697-29189530-7c3d-4333-82af-f52a35e72b88.png)


My suggestion would be to use a different translation.
Maybe:

weiter,
neu (oder wiederholen?),
abbrechen

What do you think?

**Comment by mhellmeier** [comment]
Yes, a shorter translation may work.

What do you think about changing the `height` of all buttons to a larger `min` value?

**Comment by andi34** [comment]
Ich habe die Übersetzung angepasst, bitte aktualisiere auf die aktuelle dev branch gib bescheid ob alles so passt.
